Соединение с базой данных и создание таблиц
IlyaKuzmichev/Info21_Java pull request #1
Opened 2024-10-14 17:47 UTC by openm1ke

Переделал конфиг с application.properties на application.yml

- Добавил соединение с базой данных (локально)
- Запуск sql скриптов создания схемы и таблиц

2024-10-14 17:58 UTC, IlyaKuzmichev commented
Я отвел девелоп, давай в него делать мерджи, мастер будет для стабильных версий

2024-10-14 19:49 UTC, IlyaKuzmichev commented on src/main/resources/application.yml
> +      mode: always
Это пока заглушка вместо настоящей миграции (liquibase)?

2024-10-14 19:50 UTC, IlyaKuzmichev commented on src/main/resources/application.yml
> +    show-sql: false
Если это параметр для логирования запросов, лучше на этапе разработки поставить в true, чтобы видеть что там отправляется

2024-10-14 19:52 UTC, IlyaKuzmichev commented on src/main/resources/schema.sql
> +CREATE SCHEMA IF NOT EXISTS liquibase;
Что это за схема? Или это тоже пока заглушка?

2024-10-14 20:10 UTC, IlyaKuzmichev commented on src/main/resources/db/changelog/db.changelog-1.0.yaml
> +            tableName: categories
А что это за таблица? Или это просто сэмпл? Пояснительную бригаду сюда!

2024-10-14 20:11 UTC, IlyaKuzmichev requested changes
Needs comment

2024-10-14 20:28 UTC, openm1ke commented on src/main/resources/schema.sql
> +CREATE SCHEMA IF NOT EXISTS liquibase;
это служебная схема для ликвибейс, если мы ее не укажем он по умолчанию будет создавать ее в паблик

2024-10-14 20:28 UTC, openm1ke commented on src/main/resources/db/changelog/db.changelog-1.0.yaml
> +            tableName: categories
это из моего другого проекта, просто для примера накидано, естессно все уберем и будем по взрослому вести ченжлоги в файлах ликвибейса

2024-10-14 20:30 UTC, openm1ke commented on src/main/resources/application.yml
> +      mode: always
это стартовые скрипты для создания схем и таблиц, таблицы можно перенести в ликвибейз, а вот создание схем надо оставить здесь - до инициализации вообще любых таблиц

2024-10-17 19:49 UTC, IlyaKuzmichev approved these changes

2024-10-18 23:35 UTC, closed without merging